Parameters:
  SecurityGroupDescription:
    Description: Security Groups for SSH and HTTP
    Type: String
  SecurityGroupPort1:
    Description: lock to my personal IP
    Type: Number
    MinValue: 20 # out range 19
    MaxValue: 65535
  SecurityGroupPort2:
    Description: lock to my http
    Type: Number
    MinValue: 20 # out range 19
    MaxValue: 65535
  InstanceType:
    Description: WebServer EC2 instance type (has default, AllowedValues)
    Type: String
    Default: t2.micro
    AllowedValues: #possible values
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
    ConstraintDescription: must be a valid EC2 instance type.
  DBPwd:
    NoEcho: true
    Description: The database admin account password (won't be echoed)
    Type: String
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances. Linked to AWS Parameter
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SecurityGroupIngressCIDR1:
    Description: locked to my Personal IP
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  SecurityGroupIngressCIDR2:
    Description: opened to hhtp
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  MyVPC:
    Description: VPC to operate in
    Type: AWS::EC2::VPC::Id
  MySubnetIDs:
    Description: Subnet IDs that is a List of Subnet Id
    Type: 'List<AWS::EC2::Subnet::Id>'
  PublicSubnet1:
    Type: String
  # DbSubnetIpBlocks:
  #   Description: "Comma-delimited list of three CIDR blocks"
  #   Type: CommaDelimitedList
  #   Default: "10.0.48.0/24, 10.0.112.0/24, 10.0.176.0/24"

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      #we reference the InstanceType parameter
      InstanceType: !Ref InstanceType # link to the instance type param
      KeyName: !Ref KeyName
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", ImageID]
      # here we reference an internal CloudFormation resource
      SubnetId: !Ref PublicSubnet1
      # Link EC2 instance to security group (two resources)
      SecurityGroupIds:
        - !Ref MySecurityGroup # Referencing another resources!!!
      # SecurityGroups :
      #   - !Ref MySecurityGroup

      Tags:
        - Key: Name
          Value: myInstance

  # HOMEWORK
  # CREATE AN ELATIC IP RESOURCE
  # ATTACH IP TO THE EC2 INSTANCE

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
        - CidrIp: !Ref SecurityGroupIngressCIDR1
          FromPort: !Ref SecurityGroupPort1
          ToPort: !Ref SecurityGroupPort1
          IpProtocol: tcp
        - CidrIp: !Ref SecurityGroupIngressCIDR2
          FromPort: !Ref SecurityGroupPort2
          ToPort: !Ref SecurityGroupPort2
          IpProtocol: tcp
      VpcId: !Ref MyVPC
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyEC2Instance
Mappings:
  RegionMap: 
    us-east-1: 
      "ImageID": "ami-0ff8a91507f77f867"
    us-west-1: 
      "ImageID": "ami-0bdb828fd58c52235"
    eu-west-1: 
      "ImageID": "ami-047bb4163c506cd98"
    ap-southeast-1: 
      "ImageID": "ami-08569b978cc4dfa10"
    ap-northeast-1: 
      "ImageID": "ami-06cd52961ce9f0d85"


Outputs:
  SSHSecurityGroup:
    Description: The SSH Security Group for our Company
    Value: !Ref MySecurityGroup # SG name
    Export: # Make the output available to re-use
      Name: SecurityGroupSSH # variable need to be GLOBALLY UNIQUE
  HTTPSecurityGroup:
    Description: The HTTP Security Group for our Company
    Value: !Ref MySecurityGroup # SG name
    Export: # Make the output available to re-use
      Name: SecurityGroupHTTP # variable need to be GLOBALLY UNIQUE
  EC2Intance:
    Description: Type of Instance
    Value: !Ref MyEC2Instance # SG name
    Export: # Make the output available to re-use
      Name: OurEc2 # variable need to be GLOBALLY UNIQUE